change SwiftyJSON dependency to 2.3.1 in readme
isExists() for JSON has not been add upon SwiftyJSON 2.3.1, and is renamed to exists() in this later PR: https://github.com/SwiftyJSON/SwiftyJSON/pull/457.

Specifying "~> 2.3.0" might not work, and let users run into the following error:

```
error: value of type 'JSON' has no member 'isExists'
```